# Generated by Django 3.1.2 on 2020-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='noOdItems',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
