# Generated by Django 3.1.2 on 2020-10-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orders_nooditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='restaurantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
